# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Macho',
            fields=[
                ('macho_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('mean_mag', models.FloatField(default=0.0)),
                ('median_mag', models.FloatField(default=0.0)),
                ('periodicity', models.BooleanField(default=True)),
                ('period', models.FloatField(default=0.0)),
            ],
        ),
    ]
