# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mag', models.FloatField(default=0.0)),
                ('mjg', models.FloatField(default=0.0)),
                ('macho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macho.Macho')),
            ],
        ),
    ]
