# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macho', '0002_machodetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machodetail',
            old_name='mjg',
            new_name='mjd',
        ),
    ]
