# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macho', '0004_auto_20160713_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='macho',
            name='true_label',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
