# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macho', '0005_macho_true_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='machodetail',
            name='err',
            field=models.FloatField(default=0.0),
        ),
    ]
