# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullvote',
            name='milliseconds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='milliseconds',
            field=models.BigIntegerField(default=0),
        ),
    ]
