# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('hits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=15, null=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Expert')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hits.MACHOObject')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('expert', 'object', 'question')]),
        ),
        migrations.AlterUniqueTogether(
            name='pendingquestion',
            unique_together=set([('expert', 'object', 'question')]),
        ),
    ]
