# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votehits',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='votehits',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='votehits',
            name='hits',
        ),
        migrations.DeleteModel(
            name='VoteHits',
        ),
    ]
