# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 20:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='gender',
        ),
        migrations.AddField(
            model_name='expert',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 22, 20, 59, 59, 388380, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
